Curb 4371 adjustments for dynamic yield
shopgate-professional-services/ext-product-recommendations pull request #10
Opened 2024-08-21 07:52 UTC by SaschaKrist

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix
- [x] New feature
- [ ] This change requires a documentation update

2024-08-27 09:44 UTC, fkloes requested changes

2024-08-27 09:44 UTC, fkloes commented on CHANGELOG.md
> +- Adjust ProductSlider scope for Recommendations needed for tracking
please rephrase this a bit

2024-08-27 09:44 UTC, fkloes commented on frontend/components/Slider/index.jsx
> +        scope={{
please use the new prop that we discussed to inject additional data to the `navigate` action. the `recommendationScope` object also needs to contain `type`, so that you can invoke the selectors inside the other extension with all required properties.

a value for the `scope` prop could be `productRecommendations` (we also use camel case for the `subType` at other places)

2024-08-28 12:29 UTC, SaschaKrist commented on frontend/components/Slider/index.jsx
> +        scope={{
done as discussed

2024-08-28 12:35 UTC, SaschaKrist commented on CHANGELOG.md
> +- Adjust ProductSlider scope for Recommendations needed for tracking
done

2024-08-30 12:26 UTC, fkloes requested changes

2024-08-30 12:26 UTC, fkloes commented on frontend/components/Slider/index.jsx
> +            id,
`type` is still missing in the `recommendationScope` object. it's needed for the selectors inside the dynamic yield extension to work.

2024-08-30 12:30 UTC, fkloes approved these changes

2024-08-30 12:30 UTC, fkloes commented on frontend/components/Slider/index.jsx
> +            id,
type was still missing. i've added it.

2024-08-30 14:24 UTC, merged