PS-130 Flexible campaigns
shopgate-professional-services/ext-product-recommendations pull request #9
Opened 2024-07-02 08:20 UTC by patrick-scherer

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix
- [ ] New feature
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I updated the CHANGELOG.md

2024-07-03 12:42 UTC, fkloes requested changes

2024-07-03 12:42 UTC, fkloes commented on frontend/actions/index.js
> +        requestOptions,
as far as i understand, there are multiple extensions that provide an implementation for the `shopgate.getProductRecommendations` pipeline. when you always add `requestOptions` to the input parameters, those pipelines will throw errors since they don't know this input parameter.

please only add `requestOptions` to the input when it contains request options.

2024-07-04 10:07 UTC, patrick-scherer commented on frontend/actions/index.js
> +        requestOptions,
done

2024-07-16 13:24 UTC, fkloes approved these changes

2024-08-06 09:12 UTC, merged